### ISSUE TITLE
incorrrect TVConfigURL

### ISSUE THREAD

**Issue by tariqinaam** [jwplayer/appletv#38]
TVConfigURL is set to "https://tvos.jwpsrv.com/resources/configs" where as it should point to relative base url which would be 
static let TVConfigURL = "\(AppDelegate.TVBaseURL)/resources/configs"

NOTE: Existing url would only work with demo api key, once you swtich it to your accoutn, you will get error following error on App launch:
"negative or zero item sizes are not supported in the flow layout"

**Comment by johnluther** [comment]
Thanks, Tariq, we will look into it. We're working on a new versioning scheme for the next release, /current might have gotten from develop into master by accident.

JL
